### ISSUE TITLE
Fail launch test page

### ISSUE THREAD

**Issue by felixzapata** [icoloma/koliseo-agenda#1]
Hi, following the steps to run the application it fails because there is no `gulpfile.js`. 

I don´t know if maybe is missing the process to compile the final `gulpfile.js` from the original `gulpfile.babel.js`. I´ve checked in the package file but I do not find a post install process to do something like that or related.

Regards.

**Comment by ccoloma** [comment]
You don't need any proccess to compile a final gulpfile.js file, it works with the gulpfile.babel.js one. Which versions of node and npm do you have?

**Comment by felixzapata** [comment]
Hi, v4.1.1 and 2.14.4. In my Ubuntu laptop it works. 

I will try later with the versions I have installed in my iMac.

Thanks.

**Comment by felixzapata** [comment]
Hi, in the iMac with node 5.0.0 and npm 3.3.6 when I try to run (after install the node packages) the serve task via `gulp serve`:
```Terminal
[20:41:00] No gulpfile found
```
Regards.

**Comment by icoloma** [comment]
The project has moved from gulp to webpack. Please let me know if you find any issues with the next build system.
